// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqFUbIj4ms0KEodokmjl4gFJUXcdpF9w',
    appId: '1:337083321447:web:03984d78fa4481f8bf98c2',
    messagingSenderId: '337083321447',
    projectId: 'app-psico-77804',
    authDomain: 'app-psico-77804.firebaseapp.com',
    storageBucket: 'app-psico-77804.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX8n-DG4Cy8sJ9T2_d2Ni-orxpk20H6CY',
    appId: '1:337083321447:android:32cb54a6778565ccbf98c2',
    messagingSenderId: '337083321447',
    projectId: 'app-psico-77804',
    storageBucket: 'app-psico-77804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEuYfz_9WDGVbvWkYq0Tt7RAiZTBaffec',
    appId: '1:337083321447:ios:90e5d60bca1e4b88bf98c2',
    messagingSenderId: '337083321447',
    projectId: 'app-psico-77804',
    storageBucket: 'app-psico-77804.firebasestorage.app',
    iosBundleId: 'com.example.appPsico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEuYfz_9WDGVbvWkYq0Tt7RAiZTBaffec',
    appId: '1:337083321447:ios:90e5d60bca1e4b88bf98c2',
    messagingSenderId: '337083321447',
    projectId: 'app-psico-77804',
    storageBucket: 'app-psico-77804.firebasestorage.app',
    iosBundleId: 'com.example.appPsico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTqFUbIj4ms0KEodokmjl4gFJUXcdpF9w',
    appId: '1:337083321447:web:3faa8fe0eaa44568bf98c2',
    messagingSenderId: '337083321447',
    projectId: 'app-psico-77804',
    authDomain: 'app-psico-77804.firebaseapp.com',
    storageBucket: 'app-psico-77804.firebasestorage.app',
  );
}
